val places = listOf(
    "Adrijos jūra",
    "Amundseno jūra",
    "Andamadų jūra",
    "Arabijos jūra",
    "Azovo jūra",
    "Bafino jūra",
    "Balearų jūra",
    "Balio jūra",
    "Barenco jūra",
    "Belinshauzeno jūra",
    "Beringo jūra",
    "Bismarko jūra",
    "Boforto jūra",
    "Čiukčių jūra",
    "Egėjo jūra",
    "Filipinų jūra",
    "Grenlandijos jūra",
    "Japonijos jūra",
    "Javos jūra",
    "Jonijos jūra",
    "Karibų jūra",
    "Karos jūra",
    "Kaspijos jūra",
    "Koralų jūra",
    "Labradoro jūra",
    "Laptevų jūra",
    "Lazarevo jūra",
    "Ligūrijos jūra",
    "Marmuro jūra",
    "Norvegijos jūra",
    "Ochotsko jūra",
    "Rytų Kinijos jūra",
    "Rytų Sibiro jūra",
    "Roso jūra",
    "Saliamono jūra",
    "Sargaso jūra",
    "Tasmano jūra",
    "Timoro jūra",
    "Tirėnų jūra",
    "Vedelio jūra",
    "----",
    "Bab el Mandebas sąsiauris",
    "Skagerakas sąsiauris",
    "Beringo sąsiauris",
    "Bosforo sąsiauris",
    "Dardanelų sąsiauris",
    "Kategatas sąsiauris",
    "Didysis Beltas sąsiauris",
    "Dreiko sąsiauris",
    "Lamanšo sąsiauris",
    "Pa de Kale sąsiauris",
    "Gibraltaro sąsiauris",
    "Magelano sąsiauris",
    "Malakos sąsiauris",
    "Mozambiko sąsiauris",
    "Singapūro sąsiauris",
    "Sundos sąsiauris",
    "Eresunas sąsiauris",
    "Mažasis Beltas sąsiauris",
    "----",
    "Amundseno įlanka",
    "Hadsono įlanka",
    "Kalifornijos įlanka",
    "Benino įlanka",
    "Biskajos įlanka",
    "Aliaskos įlanka",
    "Fandžio įlanka",
    "Gvinėjos įlanka",
    "Hondūro įlanka",
    "Persijos įlanka",
    "Meksikos įlanka",
    "Adeno įlanka",
    "Bengalijos įlanka",
    "Didžioji įlanka",
    "Australijos įlanka",
    "Omano įlanka",
    "Sueco įlanka",
    "Suomių įlanka",
    "Botnijos įlanka",
    "Rygos įlanka",
    "Gdansko įlanka",

    "----",
    "Panamos kanalas",
    "Sueco kanalas",
    "Korinto kanalas",
    "Kylio kanalas",

    "----",

    "Aliaskos pusiasalis",
    "Kalifornijos pusiasalis",
    "Viktorijos sala",
    "Bafino Žemė",
    "Labradoro pusiasalis",
    "Grenlandija",
    "Niufaundelndas",
    "Islandija",
    "Floridos pusiasalis",
    "Didieji Antilai",
    "Mažieji Antilai",
    "Jukatano pusiasalis",
    "Galapagai",
    "Folklando salos",
    "Antarktidos pusiasalis",
    "Azorai",
    "Kanarai salos",
    "Žaliojo Kyšulio salos",
    "Madagaskaras",
    "Somalio pusiasalis",
    "Arabijos pusiasalis",
    "Indokinijos pusiasalis",
    "Naujoji Žemė",
    "Kamčatka",
    "Sachalinas",
    "Hokaidas",
    "Honšiu",
    "Taivanas",
    "Filipinai",
    "Kalimantanas",
    "Sumatra",
    "Java",
    "Sulavesis",
    "Naujoji Gvinėja",
    "Keip Jorko pusiasalis",
    "Šri Lanka",
    "Tasmanija",
    "Naujoji Zelandija",
    "Ugnies Žemė",
    "Jutlandijos pusiasalis",
    "Skandinavijos pusiasalis",
    "Apeninų pusiasalis",
    "Pirėnų pusiasalis",
    "Balkanų pusiasalis",
    "Gotlandas",
    "Elandas",
    "Sarema",
    "Riugenas",
    "Bornholmas",
    "Hijuma sala",
    "Olandų",
    "Korėjos sala",
    "Kolos pusiasalis",
    "Taimyro pusiasalis",
    "Japonijos salos",
    "Hebridai",
    "Havajai",
    "Didžiosios",
    "Sundos sala",
    "Mažosios Sundos sala",
    "Malajų salos",
)
